### ISSUE TITLE
Duplicate events data in Redshift

### ISSUE THREAD

**Issue by MacHu-GWU** [18F/identity-analytics-etl#135]
## User story

I would like to improve data quality in Redshift by removing duplicate data.

**Context**:

IDP App generates log and posts log to AWS Cloudwatch. There are lots of duplicate events data observed in our log file. Example:

```
2000-01-01 10:00:00; abcdefg-1234567; {event_id: abcdefg-1234567, data: {key: value ...}}
2000-01-01 20:00:00; hencuzs-0000000; {event_id: abcdefg-1234567, data: {key: value ...}}
2000-01-01 10:00:00; abcdefg-1234567; {event_id: abcdefg-1234567, data: {key: value ...}}
2000-01-01 20:00:00; yoziemn-0000000; {event_id: abcdefg-1234567, data: {key: value ...}}
2000-01-01 10:00:00; abcdefg-1234567; {event_id: abcdefg-1234567, data: {key: value ...}}
```

1. The **lambda function doesn't handle duplicate events** within a single log file.
2. Redshift doesn't have ``unique primary key`` constrain.

AWS Official Document recommend do it [This way](https://docs.aws.amazon.com/redshift/latest/dg/t_updating-inserting-using-staging-tables-.html) to avoid duplicate data. But our ETL pipeline just directly copy s3 file to redshift.

## Notes

**What is the value to the user in this story?**

1. **Improve Data Accuracy**: Some existing **analytic script may not reflect the accurate number** because of the duplicate data, for example, **login successful rate**, number of login attempts having duplicates.
2. **Ease SQL development**: We have to manually take care of duplication data in the analysis, which is unnecessarily complicated. (lots of unnecessary ``DISTINCT``, ``GROUP BY``)

**Available Solutions**:

1. Solve duplicate data before data reaching Redshift: Introduce the new insert-new-data logic.
2. Remove duplicate data from Redshift: Implement software to clean up duplication in redshift.

## Acceptance Criteria

- [ ] Analysis how come having duplicate data.
- [ ] Finalize the solution to remove duplicate data.
- [ ] Implement / Test the solution
- [ ] Document Everything

## Tasks to complete in the story

Same as Acceptance Criteria

## Definition of Done

- [ ] Pull requests meet the technical definition of done
- [ ] Usability tested

**Comment by MacHu-GWU** [comment]
Will close this issue, and link to this issue when another Epic for duplicate data been created.

**Comment by lauraGgit** [comment]
@MacHu-GWU while we're waiting on some of the definitional stuff to sort itself out, i'm wondering if there is a way for your to run this on a clone of our main redshift data source?

**Comment by lauraGgit** [comment]
We don't have a way of currently doing this on a separate instance of redshift

**Comment by lauraGgit** [comment]
Migrated to JIRA
