### ISSUE TITLE
Generate lifetime proofing rate

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#167]
## User story
As a perspective agency partner, I would like to know LG's proofing rate, so that I can better compare LG to its competitors.

## Notes
* What is the value to the user in this story?*
Proofing rate is a key market research tool in assessing whether not to adopt LG, this will help make informed decisions on that.

Also, helps assess how good our proofing product is.

- substantial feature change. Once we implement docAuth, would be more useful. Right now hard fail for users who are in place.

- want to get it in sync with scale of RRB.

### Definition of Metric
The success rate of Login.gov to verify an individual.

### Initial Calculation of metric
* Number users that successfully the proofed process over the total number of users that began the proofing process since the beginning of LG offering proofing. 

* What are things we should consider when making this story *
In the future we will want to break it down by step

## Acceptance Criteria
- [ ] A biz person can generate the most up to date proofing rate.
- [ ] there is a published definition of this metric

## Tasks to complete the story
- [ ] Creating documentation
- [ ] Identifying how the calculation is made

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by MacHu-GWU** [comment]
# This issue is blocked by lack of Doc Auth relative data.

## Definition: LG Proofing Process

The process to associate the ``real world person identity`` to a login.gov ``email / password account``. Currently we use ``doc auth``.  **The doc auth workflow is defined here** https://github.com/18F/identity-idp/pull/2688#issuecomment-446847955

## Lack of Doc Auth Data

We have two places potentially having Doc Auth relative data, `Redshift` and `IDP DB`.

**Redshift**:

All events data are stored in Table(``events``). Based on this event name definition https://github.com/18F/identity-idp/blob/master/app/services/analytics.rb#L61, `'Doc Auth'` is the **event name for doc auth**. However, `SELECT COUNT(*) FROM events WHERE events.name = 'Doc Auth'` **returns 0 rows**.

**IDP DB**:

All events data are stored in Table(``events``). Based on the event id code defined here https://github.com/18F/identity-idp/blob/master/app/models/event.rb, looks like **Non doc auth relative events are stored**. 
There is another `doc_auth` table, but **there’s no Data in it**.

**We need further investigation on where can we get doc auth relative data to proceed.**

**Comment by lauraGgit** [comment]
Migrated to Jira
