### ISSUE TITLE
Generate proofing rate by specified time line

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#168]
## User story
As a prospective agency partner, I would like to know LG's proofing for a specific time range, so that I can better compare LG to its competitors.

## Notes
* What is the value to the user in this story?*
Proofing rate is a key market research tool in assessing whether not to adopt LG, this will help make informed decisions on that.

Can leverage what was created in #167 

Also, helps assess how good our proofing product is.

### Definition of Metric
The success rate of Login.gov to verify an individual for a specific time period.

### Initial Calculation of metric
* Number users that successfully the proofed process over the total number of users that began the proofing process for a set amount of time. 

* What are things we should consider when making this story *
In the future we will want to break it down by step

## Acceptance Criteria
- [ ] A biz person can retrieved the proofing rate for a specific time.
- [ ] there is a published definition of this metric

## Tasks to complete the story
- [ ] Creating documentation

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Migrated to Jira
