### ISSUE TITLE
Generate Lifetime Login Success Rate

### ISSUE THREAD

**Issue by MacHu-GWU** [18F/identity-analytics-etl#169]
## User story

As a member of agency oversight Capital Planning and Investment Control(CPIC) and the product team, I would like to know the public authentication lifetime login success rate, so that I know the AAL1/AAL2 process meets public user needs.

## Notes

* What is the value to the user in this story?*

If it is too low, it helps the team to build a better experience.

* What are things we should consider when making this story *
- this counts for both AAL1/AAL2
- for a future story want to break out AAL1 and AAL2

## Acceptance Criteria

- [ ] A biz person generates the most up to date login success rate.
- [ ] there is a published definition of this metric

## Tasks to complete the story

- [ ] Identify the query that creates these numbers
- [ ] Creating documentation

## Definition of Done

- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by MacHu-GWU** [comment]
@lauraGgit I think we need to come up a more specific definition of **TERM**(``Login Success Rate``)

Literally, a ``success rate`` = ``success count`` / ``attempts count``, 

- Definition of **TERM**(``Login``): **email password login** or **MFA login**? Since MFA is our core business, I assume **MFA login** is the case here (Correct me if I am wrong).
- Definition of **TERM**(``Attempts``): This needs more discussion.

Thinking about the case below, this user creates three sessions, and the time between 1th and 2nd is **very short**, maybe he just logged out and started over. **And the user tried three times with MFA login, and only the last one succeeded in session 1**.

**Here's question**:

- **In session 1**, is ``attempt count = 1 or 3``?
- **In this dataset**, is ``total attempts count = 3 (three sessions) or 5 (3 attempts in first session, and 1 attempts in second and third)``?

name | user_agent | user_ip | session_id | time | success
-- | -- | -- | -- | -- | --
Email and Password Authentication | iPhone ... | 99.203.29.90 | 1 | 2018-07-02 10:32:01 | TRUE
OTP: Delivery Selection | iPhone ... | 99.203.29.90 | 1 | 2018-07-02 10:32:03 | TRUE
Multi-Factor Authentication: enter OTP visited | iPhone ... | 99.203.29.90 | 1 | 2018-07-02 10:32:05 |  
**Multi-Factor Authentication** | iPhone ... | 99.203.29.90 | 1 | 2018-07-02 10:32:14 | FALSE
**Multi-Factor Authentication** | iPhone ... | 99.203.29.90 | 1 | 2018-07-02 10:32:19 | FALSE
**Multi-Factor Authentication** | iPhone ... | 99.203.29.90 | 1 | 2018-07-02 10:32:24 | TRUE
OpenID Connect: authorization request | iPhone ... | 99.203.29.90 | 1 | 2018-07-02 10:32:25 | TRUE
Logout Initiated | iPhone ... | 99.203.29.90 | 1 | 2018-07-02 10:32:41 | TRUE
OTP: Delivery Selection | iPhone ... | 99.203.29.90 | 2 | 2018-07-02 10:33:49 | TRUE
Email and Password Authentication | iPhone ... | 99.203.29.90 | 2 | 2018-07-02 10:33:49 | TRUE
Multi-Factor Authentication: enter OTP visited | iPhone ... | 99.203.29.90 | 2 | 2018-07-02 10:33:50 |  
**Multi-Factor Authentication** | iPhone ... | 99.203.29.90 | 2 | 2018-07-02 10:34:09 | TRUE
OpenID Connect: authorization request | iPhone ... | 99.203.29.90 | 2 | 2018-07-02 10:34:10 | TRUE
OTP: Delivery Selection | iPhone ... | 184.206.210.95 | 3 | 2018-07-03 11:58:54 | TRUE
Email and Password Authentication | iPhone ... | 184.206.210.95 | 3 | 2018-07-03 11:58:54 | TRUE
Multi-Factor Authentication: enter OTP visited | iPhone ... | 184.206.210.95 | 3 | 2018-07-03 11:58:55 |  
**Multi-Factor Authentication** | iPhone ... | 184.206.210.95 | 3 | 2018-07-03 11:59:09 | TRUE
OpenID Connect: authorization request | iPhone ... | 184.206.210.95 | 3 | 2018-07-03 11:59:09 | TRUE

**Comment by MacHu-GWU** [comment]
@lauraGgit OK, so let's wait for further instruction about the definition.

**Comment by lauraGgit** [comment]
Still working on it from a google analytics perspective.
having a discussion on the definitions tomorrow

**Comment by lauraGgit** [comment]
migrated to JIRA
