### ISSUE TITLE
Generate Login Success Rate by time range

### ISSUE THREAD

**Issue by MacHu-GWU** [18F/identity-analytics-etl#170]
## User story

As a member of agency oversight (CPIC) and product team, **I would like to know the public authentication login success rate changing over time and its trends**, so that I know the AAL1/AAL2 process meets public user needs over a specified period of time.

## Notes

* What is the value to the user in this story?*

If it is too low, it helps the team to build a better experience.

* What are things we should consider when making this story *

## Acceptance Criteria

- [ ] A biz person generates the login success rate time series in a specific time range.
- [ ] there is a published definition of this metric

## Tasks to complete the story

- [ ] Creating documentation
- [ ] Identitfy the query creates these numbers

## Definition of Done

- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
migrated in jira
