### ISSUE TITLE
SPIKE: Assess Quicksite usage

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#171]
## User story
As an operations person, I would like to know whether quicksite is worth maintaining, so that I can decide whether or not to keep it.

## Notes
* What is the value to the user in this story?*
- It's unclear how/ whether individuals are using the quicksite, especially since quality is not great.
- see if there's access data maybe from cloud trail.

* What are things we should consider when making this story *
- Time bound: 2 days

## Acceptance Criteria
- [ ]  Decision on how to proceed with the quicksite.
- [ ] If proceeding adding stories to the backlog on how to adapt the quicksite.
- [ ] Document the decision

## Tasks to complete the story
- [x] Find internally if there are users...ask them how they are using it
- [x] Identify service providers with access..contact them to see how/if they are using it.
- [x] Identify best place for where to document decision

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by MacHu-GWU** [comment]
Assess Quicksite Usage
==============================================================================

Relative Issue: https://github.com/18F/identity-analytics-etl/issues/171


What is QuickSight?
------------------------------------------------------------------------------

It is like a AWS powered Tableau, allow user to create data visualization dashboard with any data source.



How's QuickSight users account been created?
------------------------------------------------------------------------------

There are two ways of creating QuickSight account:

1. IAM Access: Use the ``18f-identity`` production AWS Account (QuickSight is in this account) IAM role if you have QuickSight access policy.
2. Email Access: Admin User with the AWS IAM access can create user account for others, it is an email / password only access.

Only a few people has the ``IAM Access``, mostly developers.

- Mossadeq Zia
- Andy Brody
- Justin Grevich
- Sanhe Hu

Most of users, especially external users are using ``Email Access``


QuickSight Access Monitor
------------------------------------------------------------------------------

- for ``IAM Access``: We can see login activity in the AWS IAM console
- for ``Email Access``: There's NO usage history.


QuickSight Users and Usage
------------------------------------------------------------------------------

- 21 GSA users
- 10 CBP users
- 8 Other users
- 39 total users

Their email can be found at https://docs.google.com/spreadsheets/d/1K_tl8QeEBo0POs9nUqsRGH6J9azy_QmtU0LXzYsEJ4Y/edit?usp=sharing

DaveJones (2019-01-28):
    @mossadeq and the DevOps team just did an “audit” of the quicksight user-base.  Most of the users are external to login.gov as part of sales and agency integrations

    over half the folks invited seem to have never created an account.

**Comment by lauraGgit** [comment]
about to send an email, once we get coordination with integration on reaching out to them

**Comment by MacHu-GWU** [comment]
@lauraGgit since we use doc as part of the code pattern, I just link the files change in the PR.

**Comment by MacHu-GWU** [comment]
Will be solved by #177

**Comment by lauraGgit** [comment]
need to discuss internally about how to reach out to existing users.

**Comment by lauraGgit** [comment]
coordinated with @amoose and sent out question email.

**Comment by lauraGgit** [comment]
Waiting on responses from partners
