### ISSUE TITLE
SPIKE: Identify interstitial/welcome login page options

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#174]
## User story
As a member of the public, I would like to login in more quickly, so that I can get back to the the app i want to go to.

## Notes
For this page: secure.login.gov/sign_up/start (when users are coming from an agency application service provider)
* What is the value to the user in this story?*
- see [LG-938](https://cm-jira.usa.gov/browse/LG-938)
- questions to answer: new users vs number logins per month.

* What are things we should consider when making this story *

## Acceptance Criteria
- [x] Product team has user behavior data to make a determination 
- [ ] the recommendation is secondary

## Tasks to complete the story
- [x] Develop some data on helping make this decision

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
- Bounce rate for initial page
- variance among service providers
- duration on the first page
- new users vs login

**Comment by MacHu-GWU** [comment]
**This is still under editing, plz wait until you can't see this message**

If you click ``Sign In`` from any service provider, for example: www.usajog.gov, you will land https://secure.login.gov/sign_up/start?request_id=24a655b9-8e12-4ff3-ba50-4dbe3c280198

And this is the page is what we want to analyze.

Define:

initial page = /sign_up/start

## Observations

Observation Date: 2019-02-21

### Last 1 Week

- Bouncing Rate: 9.46%
- Avg Time on Initial Page: 15 sec

### Last 1 Month

- Bouncing Rate: 10.03%
- Avg Time on Initial Page: 16 sec

**Comment by MacHu-GWU** [comment]
@lauraGgit The above comment is the relative data I found from Google Analytics.

I **DON'T think** to compare metrics between ``/sign_up/start?`` vs ``/`` validate the statement that: to ``/sign_up/start?`` page, replacing the ``sign in`` button with email / password input box, **will increase or decrease our conversion rate.** because users landing ``/sign_up/start?`` and ``/`` are different group of customers.

If we can create an experiment that redirects users randomly to https://secure.login.gov/sign_up/start?request_id=usajob and https://secure.login.gov/?request_id=usajob, then we can draw some solid conclusion.

**Comment by lauraGgit** [comment]
We may have to revisit this next week when we have the `request_id` correctly set up. And we might not need the experiment for now. 

Just to clarify - the new users are the users clicking on the `https://secure.login.gov/sign_up/enter_email` vs. going to the `/` url?

**Comment by lauraGgit** [comment]
Time Range | Metrics | usajobs.gov | ttp.cbp.dhs.gov | sam.gov
-- | -- | -- | -- | --
last week | New users | 80k | 55k  | 8.6K
  | Old users | 553K | 254K | 49k

**Comment by MacHu-GWU** [comment]
@lauraGgit This is how I get New Users and Old users count from a SP, would you mind to tell me if this is method you used?

Google Analytics -> Customization -> Custom Report:

Configure Filter:

- page = /sign_up/enter_email (for New User), / (for Old User)
- previous page path = /sign_up/start
- source = usajobs.gov

**Comment by lauraGgit** [comment]
Since this sprint is now over, let's conclude this spike and I can discuss the methods at our meeting on Wednesday

**Comment by MacHu-GWU** [comment]
> request_id

Yes:

new user = /sign_up/enter_email
old user = /
