### ISSUE TITLE
Generate top help pages

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#178]
## User story
As a customer support manager, I would like to know what are the top pages in our help content, so that I can better align our help content to meet user needs.

## Notes
* What is the value to the user in this story?*
- before an upcoming content edit on the help site, knowing what pages will assist in prioritization of the content.

* What are things we should consider when making this story *
- most of this data should be in google analytics.

## Acceptance Criteria
- [ ] a customer support manager can make content decisions based on usage data from google analytics

## Tasks to complete the story
- [x] design report in GA
- [x] gather feedback from customer support
- [ ] generate second page report from /help
- [ ] generate source -> page report

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
I'm going to take a look at Google Analytics on this

**Comment by lauraGgit** [comment]
Report generated and dropped in as #login-support. Will consider this done when get the ok from support folks.

**Comment by lauraGgit** [comment]
to do: review by sources

**Comment by lauraGgit** [comment]
Dropped a few reports into the `Customer Support > Content > 2019 Content Research` folder
