### ISSUE TITLE
Task: User event action audit

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#182]
## Task
Review the event tasks in the [Analytics Controller](https://github.com/18F/identity-idp/blob/master/app/services/analytics.rb) to see if the events being logged meet our #167 Proofing rate needs > this might help us made an informed decision about whether logs/google analytics will better serve our event notification and baselining needs.

## Notes
* What is the value to the user in this story?*
Will help us create better models of normal behavior to which we can build on for monitoring anomaly.

* What are things we should consider when making this story *
- not sure what goes to kibana. but know what goes to redshift
- not current flow diagrams.

## Tasks to complete the story
- [ ] review document
- [ ] map to user flow
- [ ] consider adding PR to revised audit flow

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Done as part of #193
