### ISSUE TITLE
Investigate the Reason of having duplicate data in Redshift.

### ISSUE THREAD

**Issue by MacHu-GWU** [18F/identity-analytics-etl#186]
## Task

Find the reason of having duplicate data in Redshift, solves #135 

## Doable Tasks

- [x] Description of Reason, Document the reason in code repo.
- [ ] Actions to reproduce the duplicate data.

## Definition of Done

- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
This looks like this is now complete so closing
