### ISSUE TITLE
Generate login.gov/contact usage data

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#189]
## User story

As a user needing help I would like to get to customer support quickly.

## Notes

**What is the value to the user in this story?**
improve the information architecture of the contact site to improve the user's to resolve their own issue.

**What are things we should consider when making this story**

## Acceptance Criteria

- [ ] Customer support can make an informed decision about what kinds of info needs to be in contact/help sections of the app (also potentially adding recs for where to improve the process)

## Tasks to complete the story

- [ ] generate GA report for login.gov/contact > sources / second page / pagesviews
- [ ] add report to Drive

## Definition of Done

- [ ] Pull requests meet technical definition of done
- [ ] Usability tested
