### ISSUE TITLE
Redshift needs distribution key and data compression

### ISSUE THREAD

**Issue by MacHu-GWU** [18F/identity-analytics-etl#190]
## User story

As a Redshift developer, I would like to **improve query performance and reduce costs for storage**.

## Notes

**What is the value to the user in this story?**

- improve query performance
- reduce cost on storage
- reduced total data size also reducing work on maintenance. 

 **What are things we should consider when making this story**

Based on my analysis, our data is primarily events data. Most of our queries are based on a specific time range and specific event name. In order to leverage the distributive computation, we should

- [x] use time as sort key, boost the query
- [ ] use id as distribution key, boost the query even faster on large data set
- [ ] apply encoding algorithm to each column (the redshift analyze result are not 100% correct), data size will be reduced by 90%+ which means we can store 10 times bigger data without scaling redshift.

**Current Table Setting**:

```
 schemaname | tablename |      column      |            type             | encoding | distkey | sortkey | notnull
------------+-----------+------------------+-----------------------------+----------+---------+---------+---------
 public     | events    | id               | character varying(40)       | none     | f       |       0 | t
 public     | events    | name             | character varying(255)      | none     | f       |       0 | t
 public     | events    | user_agent       | character varying(4096)     | none     | f       |       0 | f
 public     | events    | user_id          | character varying(40)       | none     | f       |       0 | f
 public     | events    | user_ip          | character varying(50)       | none     | f       |       0 | f
 public     | events    | host             | character varying(255)      | none     | f       |       0 | f
 public     | events    | visit_id         | character varying(40)       | none     | f       |       0 | f
 public     | events    | visitor_id       | character varying(40)       | none     | f       |       0 | f
 public     | events    | time             | timestamp without time zone | none     | f       |       1 | f
 public     | events    | event_properties | character varying(4096)     | none     | f       |       0 | f
 public     | events    | success          | boolean                     | none     | f       |       0 | f
 public     | events    | existing_user    | boolean                     | none     | f       |       0 | f
 public     | events    | otp_method       | character varying(20)       | none     | f       |       0 | f
 public     | events    | context          | character varying(20)       | none     | f       |       0 | f
 public     | events    | method           | character varying(20)       | none     | f       |       0 | f
 public     | events    | authn_context    | character varying(50)       | none     | f       |       0 | f
 public     | events    | service_provider | character varying(255)      | none     | f       |       0 | f
 public     | events    | loa3             | boolean                     | none     | f       |       0 | f
 public     | events    | active_profile   | boolean                     | none     | f       |       0 | f
 public     | events    | errors           | character varying(4096)     | none     | f       |       0 | f
```

**Analysis Result**:

```
Table  |      Column      | Encoding | Est_reduction_pct
--------+------------------+----------+-------------------
 events | id               | zstd     | 49.24
 events | name             | zstd     | 93.26
 events | user_agent       | zstd     | 92.02
 events | user_id          | zstd     | 66.02
 events | user_ip          | zstd     | 66.70
 events | host             | zstd     | 99.93
 events | visit_id         | zstd     | 55.80
 events | visitor_id       | zstd     | 56.18
 events | time             | zstd     | 63.81
 events | event_properties | zstd     | 92.87
 events | success          | zstd     | 77.61
 events | existing_user    | zstd     | 98.30
 events | otp_method       | zstd     | 99.97
 events | context          | zstd     | 94.89
 events | method           | zstd     | 94.70
 events | authn_context    | zstd     | 99.96
 events | service_provider | zstd     | 99.66
 events | loa3             | zstd     | 99.99
 events | active_profile   | zstd     | 99.99
 events | errors           | zstd     | 89.93
(20 rows)
```

## Acceptance Criteria

- [ ] deep analysis about how we use Redshift, query pattern, data pattern.
- [ ] come up optimization strategy. 
- [ ] document everything.

## Tasks to complete the story

Same as Acceptance Criteria

## Definition of Done

- [ ] Pull requests meet the technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
migrated to jira
