### ISSUE TITLE
Spike: future user event monitoring tool for normal behavior

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#193]
## User story

As a product team member, I would like to be able to quickly view normal behavior patterns of end users in authentication and proofing, so that I can continuously improve the product, and set baselines for future monitoring.

## Notes

**What is the value to the user in this story?**

**What are things we should consider when making this story**
- authentication is a simpler flow
- proofing would come next
- not talking about alerting

## Acceptance Criteria

- [ ] data can be represented consistently from when the tool is adopted
- [ ] supports team members able to actionable views 
- [ ] from an end-user perspective

## Tasks to complete the story

- [ ] 

## Definition of Done

- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Have mapped out the events, and pulled initial data for cloudwatch/GA/ and redshift - the tool to pull the data is about the same and to start out we will prototype with static prototypes within the google suite until we have a better sense of what will best serve us.
