### ISSUE TITLE
As an operations team member, I would like to get a count of active users for each agency application so that I can analyze our platform adoption and develop a pricing model based on active users.

### ISSUE THREAD

**Issue by akhlaqkhan** [18F/identity-analytics-etl#194]
## User story

As an operations team member, I would like to get a count of active users for each agency application so that I can analyze our platform adoption and develop a pricing model based on active users.

## Notes

The current logic of counting active users does not seems be accurate. An active user is defined as:

- A new login.gov user who completed a sign up successfully, or
- An existing login.gov user who logged in to an agency application successfully 

## Acceptance Criteria

- A monthly breakdown of active users for each agency application, stored and updated in this sheet on monthly basis: https://docs.google.com/spreadsheets/d/1R43ogc96FNoZPZUWTj3VKwfrNTuz50cMK9ABrfTqxWA/edit#gid=1863287775 

## Tasks to complete the story

- [ ] Modify the existing SQL query that counts active users to use correct logic as defined above. 
- [ ] Run the query in PROD to get the monthly active user count per app.

## Definition of Done

- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by lauraGgit** [comment]
This has been migrated to jira- see 974/975
